# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmput404_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notify',
            name='requester_displayName',
            field=models.CharField(default=b'AuthorName', max_length=30),
        ),
        migrations.AddField(
            model_name='notify',
            name='requester_host',
            field=models.CharField(default=b'Host', max_length=100),
        ),
        migrations.AddField(
            model_name='notify',
            name='requester_id',
            field=models.CharField(default=b'id', max_length=200),
        ),
    ]
