# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmput404_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(default=b'https://cloud-dingkai.c9users.io'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='contentType',
            field=models.CharField(choices=[(b'text/plain', b'text/plain'), (b'text/markdown', b'text/markdown'), (b'application/base64', b'application/base64'), (b'image/png; base64', b'image/png;base64'), (b'image/jpeg; base64', b'image/jpeg;base64')], default=b'PUBLIC', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[(b'text/plain', b'text/plain'), (b'text/markdown', b'text/markdown'), (b'application/base64', b'application/base64'), (b'image/png; base64', b'image/png;base64'), (b'image/jpeg; base64', b'image/jpeg;base64')], default=b'text/plain', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='origin',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[(b'PUBLIC', b'Public'), (b'FOAF', b'Friend of friend'), (b'FRIENDS', b'Friends'), (b'PRIVATE', b'Private'), (b'SERVERONLY', b'Server Only')], default=b'PUBLIC', max_length=20),
        ),
    ]
