# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmput404_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='requestee_displayName',
            field=models.CharField(default=b'AuthorName', max_length=30),
        ),
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(default=b'http://127.0.0.1:8000'),
        ),
        migrations.AlterField(
            model_name='node',
            name='auth_post_url',
            field=models.CharField(default=b'author/posts/?format=json', max_length=50),
        ),
    ]
