# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmput404_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='api_prefix',
            field=models.CharField(default=b'/service', max_length=50),
        ),
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(default=b'http://127.0.0.1'),
        ),
    ]
