# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmput404_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='img',
            field=models.ImageField(default=b'images/defaultUserImage.png', upload_to=b'images/'),
        ),
    ]
