# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmput404_project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='public_post_url',
        ),
        migrations.AddField(
            model_name='node',
            name='shareImage',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='contentType',
            field=models.CharField(choices=[(b'text/plain', b'Plain'), (b'text/markdown', b'Markdown'), (b'application/base64', b'Github'), (b'image/png; base64', b'PNG'), (b'image/jpeg; base64', b'JPEG')], default=b'PUBLIC', max_length=20),
        ),
        migrations.AlterField(
            model_name='node',
            name='api_prefix',
            field=models.CharField(blank=True, default=b'/service', max_length=50),
        ),
        migrations.AlterField(
            model_name='node',
            name='auth_post_url',
            field=models.CharField(default=b'/post/?format=json', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[(b'text/plain', b'Plain'), (b'text/markdown', b'Markdown'), (b'application/base64', b'Github'), (b'image/png; base64', b'PNG'), (b'image/jpeg; base64', b'JPEG')], default=b'text/plain', max_length=20),
        ),
    ]
