# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmput404_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='temp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='temp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='temp',
            field=models.BooleanField(default=False),
        ),
    ]
