# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmput404_project', '0002_auto_20170318_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.IntegerField(choices=[(0, b'text/plain'), (1, b'text/markdown'), (2, b'application/base64'), (3, b'image/png;base64'), (4, b'image/jpeg;base64'), (5, b'github-activity')], default=0),
        ),
    ]
