# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmput404_project', '0002_auto_20170321_0651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='user',
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='origin',
            field=models.URLField(default=b'http://127.0.0.1:8000/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.URLField(default=b'http://127.0.0.1:8000/'),
        ),
    ]
