# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmput404_project', '0002_auto_20170328_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='temp',
        ),
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(default=b'https://cloud-dingkai.c9users.io'),
        ),
        migrations.AlterField(
            model_name='node',
            name='auth_post_url',
            field=models.CharField(default=b'/author/post/?format=json', max_length=20),
        ),
    ]
