# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 21:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmput404_project', '0002_auto_20170327_1925'),
        ('cmput404_project', '0002_auto_20170327_2021'),
    ]

    operations = [
    ]
