# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 03:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmput404_project', '0002_auto_20170319_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visibileto',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visibileTo', to='cmput404_project.Post'),
        ),
    ]
