# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 01:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmput404_project', '0002_auto_20170325_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisibleTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibleTo', models.URLField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visibleTo', to='cmput404_project.Post')),
            ],
        ),
        migrations.RemoveField(
            model_name='visibileto',
            name='post',
        ),
        migrations.DeleteModel(
            name='VisibileTo',
        ),
    ]
