# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmput404_project', '0002_profile_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='temp',
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='github',
            field=models.CharField(default=b'', max_length=200),
        ),
    ]
