# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmput404_project', '0003_postimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimages',
            name='post_image',
            field=models.ImageField(upload_to=b'<function uuid4 at 0x7f7a61bc5848>'),
        ),
    ]
