# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmput404_project', '0003_auto_20170329_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(default=b'https://safe-lake-64013.herokuapp.com'),
        ),
    ]
