# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmput404_project', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='can_view',
            field=models.IntegerField(choices=[(0, b'Public'), (1, b'Friends'), (2, b'Friends of friends'), (3, b'Private')], default=0),
        ),
    ]
