# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmput404_project', '0003_auto_20170316_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, default=b'', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='github',
            field=models.CharField(blank=True, default=b'', max_length=200),
        ),
    ]
