# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cmput404_project', '0004_post_can_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_uuid',
            field=models.CharField(default=uuid.uuid4, max_length=200, unique=True),
        ),
    ]
