# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmput404_project', '0004_auto_20170316_0532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
        migrations.AddField(
            model_name='profile',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='_profile_follows_+', to='cmput404_project.Profile'),
        ),
    ]
