# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 01:20
from __future__ import unicode_literals

import cmput404_project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmput404_project', '0004_auto_20170326_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimages',
            name='post_image',
            field=models.ImageField(upload_to=cmput404_project.models.content_file_name),
        ),
    ]
