# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-25 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmput404_project', '0004_auto_20170409_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(default=b'https://safe-lake-64013.herokuapp.com'),
        ),
    ]
