# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cmput404_project', '0005_post_post_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_uuid',
            field=models.CharField(default=uuid.uuid4, max_length=200),
        ),
    ]
