# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmput404_project', '0005_auto_20170316_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='cmput404_project.Profile'),
        ),
    ]
