# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 15:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmput404_project', '0006_auto_20170311_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_uuid',
            new_name='post_id',
        ),
    ]
