# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 22:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cmput404_project', '0008_auto_20170311_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_text', models.CharField(max_length=1000)),
                ('comment_date', models.DateTimeField(verbose_name=b'date commented')),
                ('comment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post_id', models.ForeignKey(db_column=b'post_id', default=b'', editable=b'False', on_delete=django.db.models.deletion.CASCADE, to='cmput404_project.Post')),
            ],
        ),
    ]
