# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmput404_project', '0009_profile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.IntegerField(choices=[(0, b'Markdown'), (1, b'Plain Text')], default=0),
        ),
    ]
