# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 22:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmput404_project', '0010_comment_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_id',
            field=models.ForeignKey(db_column=b'post_id', default=b'', editable=b'False', on_delete=django.db.models.deletion.CASCADE, to='cmput404_project.Post'),
        ),
    ]
