# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmput404_project', '0010_post_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.IntegerField(choices=[(0, b'Plain Text'), (1, b'Markdown')], default=0),
        ),
    ]
