# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmput404_project', '0012_auto_20170312_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='can_view',
            field=models.IntegerField(choices=[(0, b'Public'), (1, b'Friends'), (2, b'Friends of friends'), (3, b'Private'), (4, b'Unlisted')], default=0),
        ),
    ]
